Repository hihi-production/property-submit-form, pull requests merged in 2020-10, with the labels that each got.

#1 chage and add readme
  README.md
Labels: documentation, hacktoberfest

#3 make route for dashboard
  app/Http/Controllers/Dashboard/DashboardController.php
  resources/views/dashboard/index.blade.php
  routes/web.php
Labels: hacktoberfest

#7 create model and migration
  app/Rent.php
  database/migrations/2020_10_09_173413_create_rents_table.php
  resources/views/client/index.blade.php
  resources/views/client/partials/footer.blade.php
  resources/views/client/partials/header.blade.php
  resources/views/layouts/landing.blade.php
Labels: hacktoberfest

#8 create register
  app/Http/Controllers/Dashboard/DashboardController.php
  resources/views/dashboard/login.blade.php
  resources/views/dashboard/register.blade.php
  routes/web.php
Labels: fixit, hacktoberfest-accepted

#10 make template landing
  public/css/style.css
  resources/views/client/index.blade.php
  resources/views/client/partials/footer.blade.php
  resources/views/client/partials/header.blade.php
  resources/views/layouts/landing.blade.php
  routes/web.php
Labels: hacktoberfest-accepted

#11 add form & list for landing page
  public/css/style.css
  public/img/empty.svg
  resources/views/client/index.blade.php
  resources/views/client/partials/footer.blade.php
  resources/views/client/partials/header.blade.php
  resources/views/dashboard/index.blade.php
Labels: hacktoberfest-accepted

#12 add responsive form
  public/css/style.css
  resources/views/client/index.blade.php
Labels: hacktoberfest-accepted

#13 Login
  resources/views/dashboard/edit.blade.php
  resources/views/dashboard/index.blade.php
Labels: hacktoberfest-accepted

#14 add navbar landing
  public/css/style.css
  resources/views/client/partials/header.blade.php
Labels: hacktoberfest-accepted

#15 make list
  public/css/style.css
  public/img/eee.png
  resources/views/client/index.blade.php
Labels: hacktoberfest-accepted

#16 add image in list and make sub banner
  resources/views/client/index.blade.php
Labels: hacktoberfest-accepted

#17 add footer and add placeholder
  public/css/style.css
  resources/views/client/index.blade.php
  resources/views/client/partials/footer.blade.php
Labels: hacktoberfest-accepted
